---
version: '3.8'
services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile.release
    environment:
      RAILS_ENV: development
    depends_on:
    - pg
    - sidekiq
    - redis
  pg:
    image: postgres
    ports:
    - '5432'
  sidekiq:
    build:
      context: "."
      dockerfile: Dockerfile.release
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: development
    depends_on:
    - pg
    - redis
  redis:
    image: redis
    ports:
    - '6379'
