```Dockerfile
FROM ruby:3.1.3-alpine

ENV RAILS_ENV=development

RUN apk add --update --no-cache \
    build-base \
    nodejs \
    yarn \
    tzdata \
    postgresql-dev \
    postgresql-client \
    git

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle config set without 'production staging' && \
    bundle install

COPY . .

RUN yarn install --check-files

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
```
